### ISSUE TITLE
Q2: Brand level up task list

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/requests-for-comments#191]
## Summary 
For this next quarter I will be focusing on leveling up our branding. This will consist of a bunch of small changes, updates and edits across the website and general user interaction. I am compiling a list to help me achieve this below. 

## Goal 
Get users to (continue to) talk about PostHog's branding online.  

### Homepage 
- [ ] Beam me up hedgehog V 2.0, UFO, star trek beam, animated in anyway
- [ ] Animate Billboard truck section to look like its driving with moving ground and cloud/wind rushing past
- [ ] Future of PostHog section on homepage - make hedgehog more futuristic/explorer 
- [ ] 'Please help our conversion rate hog' - praying on his knees 
- [ ] Enclosed HogQL section on homepage (reworked layout) 
- [ ] EU vs US updated to be not curved and more stereotypical depictions of each location (humorous) 

### Product Pages
- [ ] add logo images to customer stories sidebar, will make them more easily seen and more distinguishable between eachother
- [ ] Animated beta flag on homepage carousel of products
- [ ] Update hedgehogs on carousel to be size and design consistent 
- [ ] Make hedgehogs on product carousel interactive? aka follow cursor or move when clicked 
- [ ] graphic dashboard examples on product pages instead of screenshots
- [ ] animated graph graphics on carousels 
- [ ] 'Answer all questions' sections are not made obvious that the questions are clickable- hover colour state 
- [ ] Pricing hog update on product page
- [ ] Sticky FAQ's on scroll (product page) 
- [ ] Highlighted rows when hovering on comparison chart 
- [ ] 'Whats best for you' reimagined as Pokemon style cards (powers, strengths etc)
- [ ] Web analytics features section - screenshots replaced with better graphics 
- [ ] Product OS hedgehog needs an update
- [ ] 'Boring but important' section could be made better - think silly CTA section 
- [ ] templates layout - drop down of features/quick scan of what they look like/carousel?

### Docs 
- [ ] Newsletter update how infographics are designed
- [ ] Framework guides hedgehog replacement 
- [ ] Partners of PostHog -hero image or just hedgehog related to this
- [ ] Resources images on docs are usually all the same- change this to something else
- [ ] Data warehouse illustration on docs needs updating 

### Company 
- [ ] Company page hog animation - hogs are older style branding - needs updating
- [ ] redraw james and tim - don't match newer team images 
- [ ] redo transparency hog - could be funnier 
- [ ] update map on company page - I am not in congo - misleading  

### Other
- [x] Hedgehog avatars for profiles without images (questions section) 
- [ ] Avatar library/make your own hedgehog avatar minigame
- [ ] anonymous profile image (aka no profile image image) changed to hedgehog version?
- [ ] Team profiles- some say full country names and some are just letters
- [ ] hedgehog icon for how tall company is in hedgehogs 
- [ ] update older team images to look more in keeping with newer versions 
- [ ] HogCoin visuals/merch collab

**Comment by charlescook-ph** [comment]
Worth adding some of the more 'boring' transactional pages, like [this](https://eu.posthog.com/login) or [this](https://eu.posthog.com/signup)?

(But yes I think this looks like a great list!)

**Comment by joethreepwood** [comment]
This is a fantastic list!!

**Comment by corywatilo** [comment]
## Animation

Let's make sure we're checking with Stefan on availability/interest before we prioritize any of the animation work.

## Homepage

> Enclosed HogQL section on homepage (reworked layout)

What do you mean by this?

## Product pages

> add logo images to customer stories sidebar, will make them more easily seen and more distinguishable between each other

This view is shared between multiple types of content so we don't want to make any changes to this. But we're probably going to separate out the customer stories from this template anyway, so we'll probably do something different here in the not-too-distant future.

> graphic dashboard examples on product pages instead of screenshots

We definitely want to retain product screenshots here. Okay adding graphics, but don't want to lose the ability to directly see what the product looks like. (Super important for our demographic)

> Sticky FAQ's on scroll (product page)

May end up being technically challenging with how the site is built

## Docs

> Resources images on docs are usually all the same- change this to something else

This whole page template needs to be re-worked. We used to have the different articles in the main column (vs just the sidebar) but they've been removed and now the main column of the page is missing meat.

## Other

> Team profiles- some say full country names and some are just letters

These are editable in team member profiles - just need to be updated there to be uniform
